config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/activities'
  devise_for :users
  resources :courses
  resources :lessons
  resources :users, only: [:index, :edit, :show, :update]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  include PublicActivity::Model

  friendly_id :title, use: :slugged

  validates :title, :description, :short_description, :language, :price, :level, presence: true
  
  belongs_to :user
  has_many :lessons, dependent: :destroy
  
  has_rich_text :description

  LANGUAGES = ["English", "Japanese", "Kyrgyz"]
  def self.languages
    LANGUAGES.map{ |l| [l, l] }
  end

  LEVELS = ["Beginner", "Intermediate", "Advanced"]
  def self.levels
    LEVELS.map{ |l| [l, l] }
  end
  
  def to_s
    title
  end
  
  # activities
  tracked owner: Proc.new { |controller, model| controller.current_user }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  extend FriendlyId
  belongs_to :course
  validates :title, :content, :course, presence: true

  friendly_id :title, use: :slugged
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles
  
  belongs_to :resource,
             polymorphic: true,
             optional: true
  

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
  
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :trackable

  rolify
  has_many :courses

  validate :must_have_role, on: :update

  friendly_id :email, use: :slugged

  after_create :assign_default_role

  def online?
    updated_at > 2.minutes.ago
  end

  def to_s
    email
  end

  # def username
  #   email.split("@").first.downcase
  # end

  private
  
  def assign_default_role
    self.add_role :student if self.roles.blank?
  end
  
  def must_have_role
    errors.add(:roles, 'Must have at least one role.') if roles.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit
  protect_from_forgery

  after_action :user_activity

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  include PublicActivity::StoreController

  before_action :set_global_variables, if: :user_signed_in?
  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search) # navbar search
  end

  private

  def user_activity
    current_user.try(:touch)
  end

  # pundit
  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action!'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  def show
    @lessons = @course.lessons
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @latest_courses = Course.all.order(created_at: :desc).limit(7)
  end
  
  def activities
    @activities = PublicActivity::Activity.all
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show edit update destroy]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :course_id, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "Role for #{@user.email} was updated successfully!"
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  .card-body
    = course.short_description
  .card-footer
    .text-center
      = number_to_currency course.price
  .card-footer
    .fa.fa-book
      = course.lessons.count
  .card-footer
    .row
      .col-md-6
        .fa.fa-globe-africa
        = course.language
      .col-md-6
        .text-end
          .fa.fa-signal
          = course.level
  .card-footer
    .row
      .col-md-6
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
      .col-md-6
        .text-end
          .fa.fa-chalkboard-teacher
          = course.user.email
  - if policy(course).edit?
    .card-footer
      = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' if policy(course).edit?
      = link_to 'Destroy',
          course,
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'btn btn-sm btn-danger' if policy(course).destroy?

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    = f.input :language, collection: Course.languages
    = f.input :level, collection: Course.levels
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
  .card-header
    %h1 Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', course_path(@course)

app/views/courses/index.html.haml
%h1
  Courses:
  = @courses.count

//card-columns
.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'User email', class: 'form-control form-control-sm'
      = f.submit
    .ml-2
    = link_to courses_path do
      .fa.fa-sync
  .col-md-10
    .row{"data-masonry" => "{\"percentPosition\": true }"}
      - @courses.each do |course|
        .col-sm-4.col-md-3.py-3
          = render 'course', course: course

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= @course.title
%p
.row
  .col-lg-6
    = render 'course', course: @course
  .col-lg-6
    - if @lessons.count > 0
      - @lessons.each do |lesson|
        = render 'lessons/lesson', lesson: lesson
        %p
    - else
      %h4.text-center
        There is no any lesson.

app/views/home/activities.html.haml
%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p
%ul.list-group
  -@activities.each do |activity|
    %li.list-group-item
      = activity.id
      = link_to activity.trackable_type, activity.trackable_type
      = activity.trackable_id
      = activity.key
      = activity.parameters
      = activity.owner

  

app/views/home/index.html.haml
//jumbotron
.bg-light.p-5.my-4.rounded
  .display-4
    What do you want to learn today?
  .p-4
  .navbar-nav.me-left
    = form_tag(courses_path, method: :get) do
      .input-group
        = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"area-hidden" => "true"}

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    experts
    .row
    Find the right instructor
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the comunity
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule


%hr
%h1
  Popular
.row{"data-masonry" => "{\"percentPosition\": true }"}
  - @latest_courses.each do |course|
    .col-sm-4.col-md-3.py-3
      = render 'courses/course', course: course
%hr
%h1
  Top rated
%hr
%h1
  Latest

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        (c)
        = Time.now.year
        CoursePlatform
        .row
        .fa.fa-envelope
        = mail_to 'admin@sabakta.com'
        .row
      .col-md-4
        Privacy Policy
        .row
        Terms and Conditions
      .col-md-4
        About us
        .row
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    %a.navbar-brand{:href => "#"}
      Sabakta
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if current_user
        %ul.navbar-nav.me-auto
          %li.nav-item
            = link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do
              .fa.fa-home
              Home
          %li.nav-item
            = link_to courses_path, class: "nav-link #{'active fw-bold' if current_page?(courses_path)}" do
              .fa.fa-graduation-cap
              Courses
          - if current_user.has_role?(:teacher)
            %li.nav-item
              = link_to new_course_path, class: "nav-link #{'active fw-bold' if current_page?(new_course_path)}" do
                .fa.fa-plus
                New courses
          - if current_user.has_role?(:admin)
            %li.nav-item
              = link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do
                .fa.fa-users
                Users
        %ul.navbar-nav.me-left
          = search_form_for @ransack_courses, as: :courses_search, url: :courses do |f|
            .input-group
              = f.search_field :title_cont, placeholder: 'Find a course', class: 'form-control-sm'
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"area-hidden" => "true"}
          - if current_user.has_role?(:admin)
            %li.nav-item
              = link_to home_activities_path, class: "nav-link #{'active fw-bold' if current_page?(home_activities_path)}" do
                .fa.fa-bell
                Activities
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-user
              %b= current_user.email
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                =link_to edit_user_registration_path, class: 'dropdown-item' do
                  .fa.fa-cog
                  Account settings
              %li
                =link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do
                  .fa.fa-cog
                  Sign out
      - else
        %ul.navbar-nav
          %li.nav_item= link_to 'Register', new_user_registration_path, class: 'nav-link'
          %li.nav_item= link_to 'Login', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      = content_tag :div, msg, :id => "flash_#{name}"
      %button.btn-close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button", "aria-label" => "Close"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport" }/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      Sabakta | Online Okuu
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %script{:async => "", :crossorigin => "anonymous", :integrity => "sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D", :src => "https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
    .bg-success
      = render 'layouts/footer'

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lesson) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.association :course
    = f.input :content

  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if current_page?(course_path)
      = link_to lesson.title, lesson
    - else
      = lesson.title
  .card-body
    = lesson.content
    = lesson.course
  .card-footer
    = link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Delete', lesson, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Course
      %th Content
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.course
        %td= lesson.content
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @lesson.course, course_path(@lesson.course)
\/
= @lesson.title
%p#notice= notice

= render 'lesson', lesson: @lesson

= link_to 'Back to course', course_path(@lesson.course)

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.collection_check_boxes :role_ids, Role.all, :id, :name
  = f.error :roles, class: 'text-danger'
  %hr
  = f.button :submit, class: 'btn btn-success'

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    - if user.online?
      .text-success.fa.fa-circle
    - else
      .text-danger.fa.fa-circle
    = link_to user.email, user_path(user)
  .card-footer
    Signed up
    = time_ago_in_words(user.created_at)
    ago
  .card-footer
    = 'sign_in_count:'.humanize
    = user.sign_in_count
    .row
    = 'current_sign_in_at:'.humanize
    = user.current_sign_in_at
    .row
    = 'last_sign_in_at:'.humanize
    = user.last_sign_in_at
    .row
    = 'current_sign_in_ip:'.humanize
    = user.current_sign_in_ip
    .row
    = 'last_sign_in_ip:'.humanize
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .badge.bg-success Yes
    - else
      .badge.bg-danger No
  .card-footer
    - user.roles.each do |role|
      .badge.bg-info
        = role.name
    = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning'

app/views/users/edit.html.haml
.card
  .card-header
    %h1
      Editing user role for
      = @user.email
  .card-body
    = render 'form'

= link_to 'Cancel', users_path

app/views/users/index.html.haml
.row{ 'data-masonry' => '{\"percentPosition\": true }' }
  - @users.each do |user|
    .col-sm-4.col-md-3.py-3
      = render 'user', user: user

= search_form_for @q do |f|
  = f.search_field :email_cont, placeholder: 'Email'
  = f.submit

= link_to users_path, class: 'btn btn-sm btn-secondary  ' do
  .fa.fa-sync
%table.table.table-bordered
  %thead
    %tr
      %th Id
      %th= sort_link(@q, :email)
      %th= sort_link(@q, :created_at)
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip

app/views/users/show.html.haml
= link_to 'Users', users_path
\/
= @user.email
%p
= render 'user', user: @user